[providers]
python = { version = "3.11" }
nodejs = { version = "18" }

[phases.setup]
nixPkgs = ["python311", "nodejs_18", "npm"]

[phases.install]
cmds = [
  "npm ci",
  "pip install -r requirements.txt"
]

[phases.build] 
cmds = [
  "npm run build",
  "mkdir -p static", 
  "cp -r dist/* static/ || echo 'No dist folder found'"
]

[start]
cmd = "python server.py"
