[build]
builder = "NIXPACKS"

[build.env]
NODE_VERSION = "18"

[deploy]
# Run both Node.js (port 8080) and Python (port 5000) servers
startCommand = "cd backend && node server.js & cd python-route-service && python server.py & wait"
