# railway-frontend.toml - For React frontend service
[build]
builder = "NIXPACKS"

[build.env]
NODE_VERSION = "18"

[deploy]
startCommand = "npx serve -s build"

# Build command will be: npm install && npm run build
